services:
  transfer-service:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://transfer-service-db/transfer-service-db
      POSTGRES_USERNAME: dbuser
      POSTGRES_PASSWORD: dbpassword
      SERVER_PORT: 8080
    depends_on:
      - transfer-service-db

  transfer-service-db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: transfer-service-db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data_transfer:/var/lib/postgresql/trans/data
    restart: unless-stopped

volumes:
  pg_data_transfer: